---
driver:
  name: vagrant

driver_config:
  customize:
    memory: 2048
    cpus: 2

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-6.5

suites:
  - name: fullstack
    run_list:
      - recipe[chef-server-cluster::default]
    attributes:
      ec:
        couchdb:
          enable: true
        rabbitmq:
          enable: true
        postgresql:
          enable: true
        oc_bifrost:
          enable: true
        opscode_certificate:
          enable: true
        opscode_account:
          enable: true
        opscode_solr:
          enable: true
        opscode_expander:
          enable: true
        bookshelf:
          enable: true
        opscode_org_creator:
          enable: true
        opscode_erchef:
          enable: true
        opscode_webui:
          enable: true

  - name: standalone
    run_list:
      - recipe[test::standalone_hostsfile]
      - recipe[chef-server-cluster::standalone]
      - recipe[test::admin_org]
    attributes:
    driver_config:
      network:
      - ["private_network", {ip: "33.33.33.10"}]
