name             'oc-ec'
maintainer       'Chef Software, Inc.'
maintainer_email 'ops@getchef.com'
license          'All rights reserved'
description      'A Chef cookbook from Chef for Enterprise Chef. Turtles.'
version          '0.0.4'
