name             'chef-server-cluster'
maintainer       'Chef Software, Inc.'
maintainer_email 'ops@getchef.com'
license          'Apache 2.0'
description      'A Chef cookbook from CHEF for managing Chef Server clusters. Turtles.'
version          '0.0.10'
depends          'chef-server-ingredient'
depends          'chef-vault'
