name             'oc-ec'
maintainer       'Chef'
maintainer_email 'ops@getchef.com'
license          'All rights reserved'
description      'A Chef cookbook from Chef for Enterprise Chef'
version          '0.0.2'
